### ISSUE TITLE
Fails when running after build with pyinstaller

### ISSUE THREAD

**Issue by pebu1337** [ecies/py#236]
`OSError: cannot load library 'C:\Users\pr\AppData\Local\Temp\_MEI18002\coincurve\libsecp256k1.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\pr\\AppData\\Local\\Temp\\_MEI18002\\coincurve\\libsecp256k1.dll'`

**Comment by kigawas** [comment]
It's probably a Pyinstaller config problem, maybe this can help you.

https://stackoverflow.com/questions/69682748/how-to-fix-error-with-pyinstaller-after-compilation-in-exe
