### ISSUE TITLE
Encountered error while trying to install package. ╰─> cytoolz

### ISSUE THREAD

**Issue by Rick-mad-lab** [ecies/py#256]
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cytoolz

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by 123alikaha** [comment]
download Install Microsoft Visual C++ 2019 or 2020 build-tools as 2104 old version try 2019 or 2020 as shown from https://visualstudio.microsoft.com/visual-cpp-build-tools/  then try pip to install pip install package

**Comment by Rick-mad-lab** [comment]
Ok  I did this thing and It working now
