### ISSUE TITLE
use of a not random private key

### ISSUE THREAD

**Issue by toufic0710** [ecies/py#296]
Hi, 

in your readme, you are able to encrypt/decrypt data, thank's to a private key that you got from `generate_eth_key()` function. However, I want to use a private key that comes from another algorithm, and I can't find how to do this.

I tried two things :

1. make my own private/public key have the same size as the default ones.
2. Try to define a new `object = ecies.PrivateKey()` class, assign my secret key like this `object.secret = myOwnKey`, but then when I want to `object.to_hex()`, I got this error :
`TypeError: cannot convert 'int' object to bytes`. 

Do you have an insight?

**Comment by kigawas** [comment]
Since we are directly using `coincurve`, you can check its [documentation](https://ofek.dev/coincurve/api/#coincurve.keys.PrivateKey)
