### ISSUE TITLE
How to use locally available ECC key pairs for encryption and decryption?

### ISSUE THREAD

**Issue by huoxinyang** [ecies/py#328]

**Comment by huoxinyang** [comment]
def load_ecc_private_key(filename=securemanager.private_key_file):
    with open(filename, 'rb') as f:
        if securemanager.user_pin:
            # 加载私钥
            private_key = serialization.load_pem_private_key(
                f.read(),
                password=securemanager.user_pin.encode('utf-8'),
                backend=default_backend()
            )
        else:
            # 加载私钥
            private_key = serialization.load_pem_private_key(
                f.read(),
                password=None,
                backend=default_backend()
            )
    return private_key.private_bytes(encoding=serialization.Encoding.PEM,
                                     format=serialization.PrivateFormat.TraditionalOpenSSL,
                                     encryption_algorithm=serialization.NoEncryption())
def encrypt_file(public_key, input_file, output_file):
    with open(input_file, 'rb') as f:
        plaintext = f.read()
    with open(output_file, 'wb') as f:
        encrypt_dcp = encrypt(public_key, plaintext)
        f.write(encrypt_dcp)
    return encrypt_dcp
print(load_ecc_public_key())
encrypt_file(load_ecc_public_key(), './requests_dcp.py', './encrypt_dcp.ecc')



raise ValueError('The public key could not be parsed or is invalid.')
ValueError: The public key could not be parsed or is invalid.

**Comment by huoxinyang** [comment]
The algorithm for generating key pairs is SECP256R1

**Comment by kigawas** [comment]
secp256r1 is not supported
