### ISSUE TITLE
Is your curve compatible with JavaScript's WebCrypto?

### ISSUE THREAD

**Issue by Zhaoxun** [ecies/py#333]
Here is what I get from 'console' in chrome browser's Inspection mode:
```
curve = { name: 'ECDH', namedCurve: 'P-256' };
k = await crypto.subtle.generateKey(curve, true, ['deriveKey']);
pri = await crypto.subtle.exportKey('jwk', k.privateKey);
new Uint8Array( await crypto.subtle.exportKey('raw', k.publicKey) )
```
the publicKey from WebCrypto has 65 bytes.

However, using the sample code of ecies:
```
from ecies.utils import generate_eth_key
eth_k = generate_eth_key()
len(eth_k.public_key.to_bytes())
```
It is 64 bytes.
So is the type of keys in ecies the same with the type of keys defined by 'P-256' in  Javascript's Webcrypto?

**Comment by kigawas** [comment]
p-256 is different from `secp256k1` so not compatible
