### ISSUE TITLE
New release on PyPI ?

### ISSUE THREAD

**Issue by hoh** [ecies/py#356]
Hello !

I need to use `coincurve==19` due to conflicts with other dependencies.

I see that version is now compatible with `eciespy` since #341 ( [exact lines](https://github.com/ecies/py/commit/baecf36b8d03e4c37b09d07ae1eaab5d0e4b772f#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R39) ), however this has not been published on PyPI yet (currently 0.4.1 from Nov 13, 2023).

This prevents me from uploading a new version of my library on PyPI, since pinning dependencies outside of PyPI is not allowed.

Any chance you'll publish a new release soon on PyPI ? 

Greetz.

**Comment by kigawas** [comment]
I'll release a new version soon

**Comment by kigawas** [comment]
You can now download the new version from pypi

**Comment by hoh** [comment]
Thank you for the quick response :heart:
