### ISSUE TITLE
Dedicated organization for library set

### ISSUE THREAD

**Issue by L11R** [ecies/py#83]
So issue name speaks for itself. What do you think about?

**Comment by kigawas** [comment]
from the side of simple usage:

`eciesimple`
`ecieasy`

do you have other ideas?

**Comment by L11R** [comment]
First one is better. But we could just name it `ecies` and repos will have name of language.
Example: `https://github.com/ecies/py`.

GitHub gives me 404 on it.

**Comment by kigawas** [comment]
Cool, I just created the `ecies` org

**Comment by kigawas** [comment]
If you'd like, you can also transfer the golang version into it :)

**Comment by L11R** [comment]
@kigawas done, but I lose rights, can you restore it?

**Comment by kigawas** [comment]
I add the write privilege, can you check @L11R

**Comment by L11R** [comment]
@kigawas yeah, seems like I can commit now. Do you have Telegram or sorta to quickly communicate for simple questions? I guess issues is not place for it. Or maybe we can create slack, gitter, whatever.

**Comment by kigawas** [comment]
Sent you on gitter
