### ISSUE TITLE
Allow compress public key and in encrypt and decrypt function to decrease the encrypt data size 

### ISSUE THREAD

**Issue by sagarkaurav** [ecies/py#96]
https://github.com/ecies/py/blob/1d2ceb724b248278a369b42ed728e02bf2b21312/ecies/__init__.py#L61
If we can allow to compress public key in encrypt function we can decease the final output size by 35 bytes

**Comment by kigawas** [comment]
The original design was to encrypt files, so the pub key length was not a problem

**Comment by kigawas** [comment]
Well you can use encapsulate/decapsulate to implement a compressed key version easily

**Comment by sagarkaurav** [comment]
@kigawas  still i need to modify utils file `encapsulate` and `decapsulate` function to accept compressed public key

**Comment by kigawas** [comment]
https://github.com/ecies/py/blob/master/ecies/utils.py#L141

No you don't have to.
Actually it just takes a `coincurve.Private/PublicKey` and you can construct it with either compressed or uncompressed format
